cluster_name: chess-cluster
software_environment_name: chess-env
n_workers: 50
worker_cpu: 1
worker_memory: 8
scheduler_cpu: 4
scheduler_memory: 30
game_batch_size: 30
use_local_cluster: False
timeout_per_game: 60

# # LocalConfig - Uncomment the below to run on local machine
# n_workers: 8
# game_batch_size: 6
# use_local_cluster: True
# debug: True